#!/usr/local/bin/python3
##############################################
#
# Name: Inhalt-Check
#
# Author: Peter Christen
#
# Version: 1.0
# 
# Date: 10.01.2017 1.0
#
# Purpose: Prüft ob alle Files verteilt werden
#
##############################################

import os,configparser,argparse

####Parameter auswerten
parser = argparse.ArgumentParser(description='Liest die Inventardaten des aktuellen Servers aus')
parser.add_argument('-c', action='store_true', help="Daten in CSV-Format ausgeben")
parser.add_argument('-j', action='store_true', help="Daten in Json-Format ausgeben")
parser.add_argument('-J', action='store_true', help="Daten in ein Json-File schreiben")
parser.add_argument('-l', action='store_true', help="Daten in Klar-Text  ausgeben(Default)")
args = parser.parse_args()

###Config-File einlesen
config = configparser.ConfigParser()
config.read('Inhalt.cfg')

###Config-Daten zuordnen
basistarget=config['BASIS']['target']
basisverteil=config['BASIS']['verteil']
advancedtarget=config['ADVANCED']['target']
advancedverteil=config['ADVANCED']['verteil']

###Variablen

###Funktion
def anal_files():
   file_l=[]
   vert_l=[]
   dir = os.popen("ls").readlines()
   for f in dir:
      if "Inhalt-Beispiele" in f[:-1]:
         d = open(f[:-1],"r")
         allezeilen = d.readlines()
         d.close()
         for zeile in allezeilen:
            vert_l.append(zeile[:-1])
      else:
         file_l.append(f[:-1])
   for datei in file_l:
      if datei not in vert_l and 'Inhalt' not in datei:
         print ('Datei:', datei, 'ist in keinem Verteilfile') 

###Analyse starten
anal_files()

